//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfProcesoAutenticacionCapturaHuella complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfProcesoAutenticacionCapturaHuella"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProcesoAutenticacionCapturaHuella" type="{http://casb.bytte.com.co/}ProcesoAutenticacionCapturaHuella" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfProcesoAutenticacionCapturaHuella", propOrder = {
    "procesoAutenticacionCapturaHuella"
})
public class ArrayOfProcesoAutenticacionCapturaHuella {

    @XmlElement(name = "ProcesoAutenticacionCapturaHuella", nillable = true)
    protected List<ProcesoAutenticacionCapturaHuella> procesoAutenticacionCapturaHuella;

    /**
     * Gets the value of the procesoAutenticacionCapturaHuella property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the procesoAutenticacionCapturaHuella property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcesoAutenticacionCapturaHuella().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcesoAutenticacionCapturaHuella }
     * 
     * 
     */
    public List<ProcesoAutenticacionCapturaHuella> getProcesoAutenticacionCapturaHuella() {
        if (procesoAutenticacionCapturaHuella == null) {
            procesoAutenticacionCapturaHuella = new ArrayList<ProcesoAutenticacionCapturaHuella>();
        }
        return this.procesoAutenticacionCapturaHuella;
    }

}
