//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutenticacionDactilarRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AutenticacionDactilarRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://casb.bytte.com.co/}RequestBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HuellasProceso" type="{http://casb.bytte.com.co/}ArrayOfProcesoAutenticacionCapturaHuella" minOccurs="0"/&gt;
 *         &lt;element name="ScoreRequerido" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="HuellasAProcesar" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutenticacionDactilarRequest", propOrder = {
    "huellasProceso",
    "scoreRequerido",
    "huellasAProcesar"
})
public class AutenticacionDactilarRequest
    extends RequestBase
{

    @XmlElement(name = "HuellasProceso")
    protected ArrayOfProcesoAutenticacionCapturaHuella huellasProceso;
    @XmlElement(name = "ScoreRequerido")
    protected int scoreRequerido;
    @XmlElement(name = "HuellasAProcesar")
    protected int huellasAProcesar;

    /**
     * Gets the value of the huellasProceso property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfProcesoAutenticacionCapturaHuella }
     *     
     */
    public ArrayOfProcesoAutenticacionCapturaHuella getHuellasProceso() {
        return huellasProceso;
    }

    /**
     * Sets the value of the huellasProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfProcesoAutenticacionCapturaHuella }
     *     
     */
    public void setHuellasProceso(ArrayOfProcesoAutenticacionCapturaHuella value) {
        this.huellasProceso = value;
    }

    /**
     * Gets the value of the scoreRequerido property.
     * 
     */
    public int getScoreRequerido() {
        return scoreRequerido;
    }

    /**
     * Sets the value of the scoreRequerido property.
     * 
     */
    public void setScoreRequerido(int value) {
        this.scoreRequerido = value;
    }

    /**
     * Gets the value of the huellasAProcesar property.
     * 
     */
    public int getHuellasAProcesar() {
        return huellasAProcesar;
    }

    /**
     * Sets the value of the huellasAProcesar property.
     * 
     */
    public void setHuellasAProcesar(int value) {
        this.huellasAProcesar = value;
    }

}
