//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ClienteDocumento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClienteDocumento"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://casb.bytte.com.co/}ClienteDocumentoData"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CldId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FechaRegistro" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="EnrolamientoFaceFecha" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="EnrolamientoFaceURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EnrolamientoFaceTemplate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EnrolamientoFace" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClienteDocumento", propOrder = {
    "cldId",
    "fechaRegistro",
    "enrolamientoFaceFecha",
    "enrolamientoFaceURL",
    "enrolamientoFaceTemplate",
    "enrolamientoFace"
})
public class ClienteDocumento
    extends ClienteDocumentoData
{

    @XmlElement(name = "CldId")
    protected String cldId;
    @XmlElement(name = "FechaRegistro", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaRegistro;
    @XmlElement(name = "EnrolamientoFaceFecha", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar enrolamientoFaceFecha;
    @XmlElement(name = "EnrolamientoFaceURL")
    protected String enrolamientoFaceURL;
    @XmlElement(name = "EnrolamientoFaceTemplate")
    protected String enrolamientoFaceTemplate;
    @XmlElement(name = "EnrolamientoFace")
    protected boolean enrolamientoFace;

    /**
     * Gets the value of the cldId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCldId() {
        return cldId;
    }

    /**
     * Sets the value of the cldId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCldId(String value) {
        this.cldId = value;
    }

    /**
     * Gets the value of the fechaRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * Sets the value of the fechaRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaRegistro(XMLGregorianCalendar value) {
        this.fechaRegistro = value;
    }

    /**
     * Gets the value of the enrolamientoFaceFecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEnrolamientoFaceFecha() {
        return enrolamientoFaceFecha;
    }

    /**
     * Sets the value of the enrolamientoFaceFecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEnrolamientoFaceFecha(XMLGregorianCalendar value) {
        this.enrolamientoFaceFecha = value;
    }

    /**
     * Gets the value of the enrolamientoFaceURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrolamientoFaceURL() {
        return enrolamientoFaceURL;
    }

    /**
     * Sets the value of the enrolamientoFaceURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrolamientoFaceURL(String value) {
        this.enrolamientoFaceURL = value;
    }

    /**
     * Gets the value of the enrolamientoFaceTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrolamientoFaceTemplate() {
        return enrolamientoFaceTemplate;
    }

    /**
     * Sets the value of the enrolamientoFaceTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrolamientoFaceTemplate(String value) {
        this.enrolamientoFaceTemplate = value;
    }

    /**
     * Gets the value of the enrolamientoFace property.
     * 
     */
    public boolean isEnrolamientoFace() {
        return enrolamientoFace;
    }

    /**
     * Sets the value of the enrolamientoFace property.
     * 
     */
    public void setEnrolamientoFace(boolean value) {
        this.enrolamientoFace = value;
    }

}
