//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConsultaProcesoValidacionDocumentoRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsultaProcesoValidacionDocumentoRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IdentificadorProceso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ConsultaImagenes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ConsultaInfoCodigoBarras" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ConsultaHuellas" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ConsultaScore" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultaProcesoValidacionDocumentoRequest", propOrder = {
    "identificadorProceso",
    "consultaImagenes",
    "consultaInfoCodigoBarras",
    "consultaHuellas",
    "consultaScore"
})
public class ConsultaProcesoValidacionDocumentoRequest {

    @XmlElement(name = "IdentificadorProceso")
    protected String identificadorProceso;
    @XmlElement(name = "ConsultaImagenes")
    protected boolean consultaImagenes;
    @XmlElement(name = "ConsultaInfoCodigoBarras")
    protected boolean consultaInfoCodigoBarras;
    @XmlElement(name = "ConsultaHuellas")
    protected boolean consultaHuellas;
    @XmlElement(name = "ConsultaScore")
    protected boolean consultaScore;

    /**
     * Gets the value of the identificadorProceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificadorProceso() {
        return identificadorProceso;
    }

    /**
     * Sets the value of the identificadorProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificadorProceso(String value) {
        this.identificadorProceso = value;
    }

    /**
     * Gets the value of the consultaImagenes property.
     * 
     */
    public boolean isConsultaImagenes() {
        return consultaImagenes;
    }

    /**
     * Sets the value of the consultaImagenes property.
     * 
     */
    public void setConsultaImagenes(boolean value) {
        this.consultaImagenes = value;
    }

    /**
     * Gets the value of the consultaInfoCodigoBarras property.
     * 
     */
    public boolean isConsultaInfoCodigoBarras() {
        return consultaInfoCodigoBarras;
    }

    /**
     * Sets the value of the consultaInfoCodigoBarras property.
     * 
     */
    public void setConsultaInfoCodigoBarras(boolean value) {
        this.consultaInfoCodigoBarras = value;
    }

    /**
     * Gets the value of the consultaHuellas property.
     * 
     */
    public boolean isConsultaHuellas() {
        return consultaHuellas;
    }

    /**
     * Sets the value of the consultaHuellas property.
     * 
     */
    public void setConsultaHuellas(boolean value) {
        this.consultaHuellas = value;
    }

    /**
     * Gets the value of the consultaScore property.
     * 
     */
    public boolean isConsultaScore() {
        return consultaScore;
    }

    /**
     * Sets the value of the consultaScore property.
     * 
     */
    public void setConsultaScore(boolean value) {
        this.consultaScore = value;
    }

}
