//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.bytte.schemas.ServicioAutenticacion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.bytte.schemas.ServicioAutenticacion
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaProcesoValidacionDocumento }
     * 
     */
    public ConsultaProcesoValidacionDocumento createConsultaProcesoValidacionDocumento() {
        return new ConsultaProcesoValidacionDocumento();
    }

    /**
     * Create an instance of {@link ConsultaProcesoValidacionDocumentoRequest }
     * 
     */
    public ConsultaProcesoValidacionDocumentoRequest createConsultaProcesoValidacionDocumentoRequest() {
        return new ConsultaProcesoValidacionDocumentoRequest();
    }

    /**
     * Create an instance of {@link ConsultaProcesoValidacionDocumentoResponse }
     * 
     */
    public ConsultaProcesoValidacionDocumentoResponse createConsultaProcesoValidacionDocumentoResponse() {
        return new ConsultaProcesoValidacionDocumentoResponse();
    }

    /**
     * Create an instance of {@link ProcesoAutenticacionLogResponse }
     * 
     */
    public ProcesoAutenticacionLogResponse createProcesoAutenticacionLogResponse() {
        return new ProcesoAutenticacionLogResponse();
    }

    /**
     * Create an instance of {@link ConsultaProcesoValidacionDocumentoWSQ }
     * 
     */
    public ConsultaProcesoValidacionDocumentoWSQ createConsultaProcesoValidacionDocumentoWSQ() {
        return new ConsultaProcesoValidacionDocumentoWSQ();
    }

    /**
     * Create an instance of {@link ConsultaProcesoValidacionDocumentoWSQResponse }
     * 
     */
    public ConsultaProcesoValidacionDocumentoWSQResponse createConsultaProcesoValidacionDocumentoWSQResponse() {
        return new ConsultaProcesoValidacionDocumentoWSQResponse();
    }

    /**
     * Create an instance of {@link ProcesoConsultaANI }
     * 
     */
    public ProcesoConsultaANI createProcesoConsultaANI() {
        return new ProcesoConsultaANI();
    }

    /**
     * Create an instance of {@link ProcesoANIRequest }
     * 
     */
    public ProcesoANIRequest createProcesoANIRequest() {
        return new ProcesoANIRequest();
    }

    /**
     * Create an instance of {@link ProcesoConsultaANIResponse }
     * 
     */
    public ProcesoConsultaANIResponse createProcesoConsultaANIResponse() {
        return new ProcesoConsultaANIResponse();
    }

    /**
     * Create an instance of {@link ProcesoANIResponse }
     * 
     */
    public ProcesoANIResponse createProcesoANIResponse() {
        return new ProcesoANIResponse();
    }

    /**
     * Create an instance of {@link ConversionCodigodeBarras }
     * 
     */
    public ConversionCodigodeBarras createConversionCodigodeBarras() {
        return new ConversionCodigodeBarras();
    }

    /**
     * Create an instance of {@link ConversionCodigodeBarrasResponse }
     * 
     */
    public ConversionCodigodeBarrasResponse createConversionCodigodeBarrasResponse() {
        return new ConversionCodigodeBarrasResponse();
    }

    /**
     * Create an instance of {@link ConvertClienteResponse }
     * 
     */
    public ConvertClienteResponse createConvertClienteResponse() {
        return new ConvertClienteResponse();
    }

    /**
     * Create an instance of {@link ValidacionEnrolamientoDocumentoRostro }
     * 
     */
    public ValidacionEnrolamientoDocumentoRostro createValidacionEnrolamientoDocumentoRostro() {
        return new ValidacionEnrolamientoDocumentoRostro();
    }

    /**
     * Create an instance of {@link ValidacionEnrolamientoDocumentoRequestBase }
     * 
     */
    public ValidacionEnrolamientoDocumentoRequestBase createValidacionEnrolamientoDocumentoRequestBase() {
        return new ValidacionEnrolamientoDocumentoRequestBase();
    }

    /**
     * Create an instance of {@link ValidacionEnrolamientoDocumentoRostroResponse }
     * 
     */
    public ValidacionEnrolamientoDocumentoRostroResponse createValidacionEnrolamientoDocumentoRostroResponse() {
        return new ValidacionEnrolamientoDocumentoRostroResponse();
    }

    /**
     * Create an instance of {@link ProcesoValidacionDocumentoResponse }
     * 
     */
    public ProcesoValidacionDocumentoResponse createProcesoValidacionDocumentoResponse() {
        return new ProcesoValidacionDocumentoResponse();
    }

    /**
     * Create an instance of {@link ValidacionEnrolamientoDocumento }
     * 
     */
    public ValidacionEnrolamientoDocumento createValidacionEnrolamientoDocumento() {
        return new ValidacionEnrolamientoDocumento();
    }

    /**
     * Create an instance of {@link ValidacionEnrolamientoDocumentoRequest }
     * 
     */
    public ValidacionEnrolamientoDocumentoRequest createValidacionEnrolamientoDocumentoRequest() {
        return new ValidacionEnrolamientoDocumentoRequest();
    }

    /**
     * Create an instance of {@link ValidacionEnrolamientoDocumentoResponse }
     * 
     */
    public ValidacionEnrolamientoDocumentoResponse createValidacionEnrolamientoDocumentoResponse() {
        return new ValidacionEnrolamientoDocumentoResponse();
    }

    /**
     * Create an instance of {@link AutenticacionDactilar }
     * 
     */
    public AutenticacionDactilar createAutenticacionDactilar() {
        return new AutenticacionDactilar();
    }

    /**
     * Create an instance of {@link AutenticacionDactilarRequest }
     * 
     */
    public AutenticacionDactilarRequest createAutenticacionDactilarRequest() {
        return new AutenticacionDactilarRequest();
    }

    /**
     * Create an instance of {@link AutenticacionDactilarResponse }
     * 
     */
    public AutenticacionDactilarResponse createAutenticacionDactilarResponse() {
        return new AutenticacionDactilarResponse();
    }

    /**
     * Create an instance of {@link ConsultaUsuario }
     * 
     */
    public ConsultaUsuario createConsultaUsuario() {
        return new ConsultaUsuario();
    }

    /**
     * Create an instance of {@link ConsultaUsuarioResponse }
     * 
     */
    public ConsultaUsuarioResponse createConsultaUsuarioResponse() {
        return new ConsultaUsuarioResponse();
    }

    /**
     * Create an instance of {@link UsuarioResponse }
     * 
     */
    public UsuarioResponse createUsuarioResponse() {
        return new UsuarioResponse();
    }

    /**
     * Create an instance of {@link ProcesoAutenticacionDocumento }
     * 
     */
    public ProcesoAutenticacionDocumento createProcesoAutenticacionDocumento() {
        return new ProcesoAutenticacionDocumento();
    }

    /**
     * Create an instance of {@link ArrayOfProcesoAutenticacionCapturaHuella }
     * 
     */
    public ArrayOfProcesoAutenticacionCapturaHuella createArrayOfProcesoAutenticacionCapturaHuella() {
        return new ArrayOfProcesoAutenticacionCapturaHuella();
    }

    /**
     * Create an instance of {@link ProcesoAutenticacionCapturaHuella }
     * 
     */
    public ProcesoAutenticacionCapturaHuella createProcesoAutenticacionCapturaHuella() {
        return new ProcesoAutenticacionCapturaHuella();
    }

    /**
     * Create an instance of {@link DocumentoData }
     * 
     */
    public DocumentoData createDocumentoData() {
        return new DocumentoData();
    }

    /**
     * Create an instance of {@link ANIData }
     * 
     */
    public ANIData createANIData() {
        return new ANIData();
    }

    /**
     * Create an instance of {@link RequestBase }
     * 
     */
    public RequestBase createRequestBase() {
        return new RequestBase();
    }

    /**
     * Create an instance of {@link ScoreRequest }
     * 
     */
    public ScoreRequest createScoreRequest() {
        return new ScoreRequest();
    }

    /**
     * Create an instance of {@link ClienteDocumento }
     * 
     */
    public ClienteDocumento createClienteDocumento() {
        return new ClienteDocumento();
    }

    /**
     * Create an instance of {@link ClienteDocumentoData }
     * 
     */
    public ClienteDocumentoData createClienteDocumentoData() {
        return new ClienteDocumentoData();
    }

    /**
     * Create an instance of {@link UsuarioEnrolamiento }
     * 
     */
    public UsuarioEnrolamiento createUsuarioEnrolamiento() {
        return new UsuarioEnrolamiento();
    }

    /**
     * Create an instance of {@link Usuario }
     * 
     */
    public Usuario createUsuario() {
        return new Usuario();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link ANIResponse }
     * 
     */
    public ANIResponse createANIResponse() {
        return new ANIResponse();
    }

}
