//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcesoAutenticacionCapturaHuella complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcesoAutenticacionCapturaHuella"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Imagen" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="WSQImagen" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="Template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TemplateVersion" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="IdFingerprint" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcesoAutenticacionCapturaHuella", propOrder = {
    "imagen",
    "wsqImagen",
    "template",
    "templateVersion",
    "idFingerprint",
    "url"
})
public class ProcesoAutenticacionCapturaHuella {

    @XmlElement(name = "Imagen")
    protected byte[] imagen;
    @XmlElement(name = "WSQImagen")
    protected byte[] wsqImagen;
    @XmlElement(name = "Template")
    protected String template;
    @XmlElement(name = "TemplateVersion")
    protected int templateVersion;
    @XmlElement(name = "IdFingerprint")
    protected int idFingerprint;
    @XmlElement(name = "URL")
    protected String url;

    /**
     * Gets the value of the imagen property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getImagen() {
        return imagen;
    }

    /**
     * Sets the value of the imagen property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setImagen(byte[] value) {
        this.imagen = value;
    }

    /**
     * Gets the value of the wsqImagen property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getWSQImagen() {
        return wsqImagen;
    }

    /**
     * Sets the value of the wsqImagen property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setWSQImagen(byte[] value) {
        this.wsqImagen = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the templateVersion property.
     * 
     */
    public int getTemplateVersion() {
        return templateVersion;
    }

    /**
     * Sets the value of the templateVersion property.
     * 
     */
    public void setTemplateVersion(int value) {
        this.templateVersion = value;
    }

    /**
     * Gets the value of the idFingerprint property.
     * 
     */
    public int getIdFingerprint() {
        return idFingerprint;
    }

    /**
     * Sets the value of the idFingerprint property.
     * 
     */
    public void setIdFingerprint(int value) {
        this.idFingerprint = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

}
