//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="OperacionExitosa" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="Mensaje" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MensajeOperacion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", namespace = "http://www.bytte.com.co/")
@XmlSeeAlso({
    ProcesoAutenticacionLogResponse.class,
    ProcesoANIResponse.class,
    ConvertClienteResponse.class,
    ProcesoValidacionDocumentoResponse.class,
    UsuarioResponse.class,
    ANIResponse.class
})
public class Response {

    @XmlAttribute(name = "OperacionExitosa", required = true)
    protected boolean operacionExitosa;
    @XmlAttribute(name = "Mensaje")
    protected String mensaje;
    @XmlAttribute(name = "MensajeOperacion")
    protected String mensajeOperacion;

    /**
     * Gets the value of the operacionExitosa property.
     * 
     */
    public boolean isOperacionExitosa() {
        return operacionExitosa;
    }

    /**
     * Sets the value of the operacionExitosa property.
     * 
     */
    public void setOperacionExitosa(boolean value) {
        this.operacionExitosa = value;
    }

    /**
     * Gets the value of the mensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje(String value) {
        this.mensaje = value;
    }

    /**
     * Gets the value of the mensajeOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensajeOperacion() {
        return mensajeOperacion;
    }

    /**
     * Sets the value of the mensajeOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensajeOperacion(String value) {
        this.mensajeOperacion = value;
    }

}
