//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScoreRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScoreRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Score_AutenticacionDactilar" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Score_ConANI_ANIOCR" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Score_ConANI_OCRBarCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Score_ConANI_ANIBarCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Score_ConANI_Fingerprint" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Score_SinANI_OCRBarCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Score_SinANI_Fingerprint" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_ConANI_AniOCR" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_ConANI_OCRBarcode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_ConANI_AniBarCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_ConANI_FaceMatch" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_SinANI_OCRBarcode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_SinAni_FaceMatch" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_General_Minimo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_General_Minimo_AniOCR" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_General_Minimo_OCRBarcode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Porcentaje_General_Minimo_AniBarCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScoreRequest", propOrder = {
    "scoreAutenticacionDactilar",
    "scoreConANIANIOCR",
    "scoreConANIOCRBarCode",
    "scoreConANIANIBarCode",
    "scoreConANIFingerprint",
    "scoreSinANIOCRBarCode",
    "scoreSinANIFingerprint",
    "porcentajeConANIAniOCR",
    "porcentajeConANIOCRBarcode",
    "porcentajeConANIAniBarCode",
    "porcentajeConANIFaceMatch",
    "porcentajeSinANIOCRBarcode",
    "porcentajeSinAniFaceMatch",
    "porcentajeGeneralMinimo",
    "porcentajeGeneralMinimoAniOCR",
    "porcentajeGeneralMinimoOCRBarcode",
    "porcentajeGeneralMinimoAniBarCode"
})
public class ScoreRequest {

    @XmlElement(name = "Score_AutenticacionDactilar")
    protected int scoreAutenticacionDactilar;
    @XmlElement(name = "Score_ConANI_ANIOCR")
    protected int scoreConANIANIOCR;
    @XmlElement(name = "Score_ConANI_OCRBarCode")
    protected int scoreConANIOCRBarCode;
    @XmlElement(name = "Score_ConANI_ANIBarCode")
    protected int scoreConANIANIBarCode;
    @XmlElement(name = "Score_ConANI_Fingerprint")
    protected int scoreConANIFingerprint;
    @XmlElement(name = "Score_SinANI_OCRBarCode")
    protected int scoreSinANIOCRBarCode;
    @XmlElement(name = "Score_SinANI_Fingerprint")
    protected int scoreSinANIFingerprint;
    @XmlElement(name = "Porcentaje_ConANI_AniOCR")
    protected int porcentajeConANIAniOCR;
    @XmlElement(name = "Porcentaje_ConANI_OCRBarcode")
    protected int porcentajeConANIOCRBarcode;
    @XmlElement(name = "Porcentaje_ConANI_AniBarCode")
    protected int porcentajeConANIAniBarCode;
    @XmlElement(name = "Porcentaje_ConANI_FaceMatch")
    protected int porcentajeConANIFaceMatch;
    @XmlElement(name = "Porcentaje_SinANI_OCRBarcode")
    protected int porcentajeSinANIOCRBarcode;
    @XmlElement(name = "Porcentaje_SinAni_FaceMatch")
    protected int porcentajeSinAniFaceMatch;
    @XmlElement(name = "Porcentaje_General_Minimo")
    protected int porcentajeGeneralMinimo;
    @XmlElement(name = "Porcentaje_General_Minimo_AniOCR")
    protected int porcentajeGeneralMinimoAniOCR;
    @XmlElement(name = "Porcentaje_General_Minimo_OCRBarcode")
    protected int porcentajeGeneralMinimoOCRBarcode;
    @XmlElement(name = "Porcentaje_General_Minimo_AniBarCode")
    protected int porcentajeGeneralMinimoAniBarCode;

    /**
     * Gets the value of the scoreAutenticacionDactilar property.
     * 
     */
    public int getScoreAutenticacionDactilar() {
        return scoreAutenticacionDactilar;
    }

    /**
     * Sets the value of the scoreAutenticacionDactilar property.
     * 
     */
    public void setScoreAutenticacionDactilar(int value) {
        this.scoreAutenticacionDactilar = value;
    }

    /**
     * Gets the value of the scoreConANIANIOCR property.
     * 
     */
    public int getScoreConANIANIOCR() {
        return scoreConANIANIOCR;
    }

    /**
     * Sets the value of the scoreConANIANIOCR property.
     * 
     */
    public void setScoreConANIANIOCR(int value) {
        this.scoreConANIANIOCR = value;
    }

    /**
     * Gets the value of the scoreConANIOCRBarCode property.
     * 
     */
    public int getScoreConANIOCRBarCode() {
        return scoreConANIOCRBarCode;
    }

    /**
     * Sets the value of the scoreConANIOCRBarCode property.
     * 
     */
    public void setScoreConANIOCRBarCode(int value) {
        this.scoreConANIOCRBarCode = value;
    }

    /**
     * Gets the value of the scoreConANIANIBarCode property.
     * 
     */
    public int getScoreConANIANIBarCode() {
        return scoreConANIANIBarCode;
    }

    /**
     * Sets the value of the scoreConANIANIBarCode property.
     * 
     */
    public void setScoreConANIANIBarCode(int value) {
        this.scoreConANIANIBarCode = value;
    }

    /**
     * Gets the value of the scoreConANIFingerprint property.
     * 
     */
    public int getScoreConANIFingerprint() {
        return scoreConANIFingerprint;
    }

    /**
     * Sets the value of the scoreConANIFingerprint property.
     * 
     */
    public void setScoreConANIFingerprint(int value) {
        this.scoreConANIFingerprint = value;
    }

    /**
     * Gets the value of the scoreSinANIOCRBarCode property.
     * 
     */
    public int getScoreSinANIOCRBarCode() {
        return scoreSinANIOCRBarCode;
    }

    /**
     * Sets the value of the scoreSinANIOCRBarCode property.
     * 
     */
    public void setScoreSinANIOCRBarCode(int value) {
        this.scoreSinANIOCRBarCode = value;
    }

    /**
     * Gets the value of the scoreSinANIFingerprint property.
     * 
     */
    public int getScoreSinANIFingerprint() {
        return scoreSinANIFingerprint;
    }

    /**
     * Sets the value of the scoreSinANIFingerprint property.
     * 
     */
    public void setScoreSinANIFingerprint(int value) {
        this.scoreSinANIFingerprint = value;
    }

    /**
     * Gets the value of the porcentajeConANIAniOCR property.
     * 
     */
    public int getPorcentajeConANIAniOCR() {
        return porcentajeConANIAniOCR;
    }

    /**
     * Sets the value of the porcentajeConANIAniOCR property.
     * 
     */
    public void setPorcentajeConANIAniOCR(int value) {
        this.porcentajeConANIAniOCR = value;
    }

    /**
     * Gets the value of the porcentajeConANIOCRBarcode property.
     * 
     */
    public int getPorcentajeConANIOCRBarcode() {
        return porcentajeConANIOCRBarcode;
    }

    /**
     * Sets the value of the porcentajeConANIOCRBarcode property.
     * 
     */
    public void setPorcentajeConANIOCRBarcode(int value) {
        this.porcentajeConANIOCRBarcode = value;
    }

    /**
     * Gets the value of the porcentajeConANIAniBarCode property.
     * 
     */
    public int getPorcentajeConANIAniBarCode() {
        return porcentajeConANIAniBarCode;
    }

    /**
     * Sets the value of the porcentajeConANIAniBarCode property.
     * 
     */
    public void setPorcentajeConANIAniBarCode(int value) {
        this.porcentajeConANIAniBarCode = value;
    }

    /**
     * Gets the value of the porcentajeConANIFaceMatch property.
     * 
     */
    public int getPorcentajeConANIFaceMatch() {
        return porcentajeConANIFaceMatch;
    }

    /**
     * Sets the value of the porcentajeConANIFaceMatch property.
     * 
     */
    public void setPorcentajeConANIFaceMatch(int value) {
        this.porcentajeConANIFaceMatch = value;
    }

    /**
     * Gets the value of the porcentajeSinANIOCRBarcode property.
     * 
     */
    public int getPorcentajeSinANIOCRBarcode() {
        return porcentajeSinANIOCRBarcode;
    }

    /**
     * Sets the value of the porcentajeSinANIOCRBarcode property.
     * 
     */
    public void setPorcentajeSinANIOCRBarcode(int value) {
        this.porcentajeSinANIOCRBarcode = value;
    }

    /**
     * Gets the value of the porcentajeSinAniFaceMatch property.
     * 
     */
    public int getPorcentajeSinAniFaceMatch() {
        return porcentajeSinAniFaceMatch;
    }

    /**
     * Sets the value of the porcentajeSinAniFaceMatch property.
     * 
     */
    public void setPorcentajeSinAniFaceMatch(int value) {
        this.porcentajeSinAniFaceMatch = value;
    }

    /**
     * Gets the value of the porcentajeGeneralMinimo property.
     * 
     */
    public int getPorcentajeGeneralMinimo() {
        return porcentajeGeneralMinimo;
    }

    /**
     * Sets the value of the porcentajeGeneralMinimo property.
     * 
     */
    public void setPorcentajeGeneralMinimo(int value) {
        this.porcentajeGeneralMinimo = value;
    }

    /**
     * Gets the value of the porcentajeGeneralMinimoAniOCR property.
     * 
     */
    public int getPorcentajeGeneralMinimoAniOCR() {
        return porcentajeGeneralMinimoAniOCR;
    }

    /**
     * Sets the value of the porcentajeGeneralMinimoAniOCR property.
     * 
     */
    public void setPorcentajeGeneralMinimoAniOCR(int value) {
        this.porcentajeGeneralMinimoAniOCR = value;
    }

    /**
     * Gets the value of the porcentajeGeneralMinimoOCRBarcode property.
     * 
     */
    public int getPorcentajeGeneralMinimoOCRBarcode() {
        return porcentajeGeneralMinimoOCRBarcode;
    }

    /**
     * Sets the value of the porcentajeGeneralMinimoOCRBarcode property.
     * 
     */
    public void setPorcentajeGeneralMinimoOCRBarcode(int value) {
        this.porcentajeGeneralMinimoOCRBarcode = value;
    }

    /**
     * Gets the value of the porcentajeGeneralMinimoAniBarCode property.
     * 
     */
    public int getPorcentajeGeneralMinimoAniBarCode() {
        return porcentajeGeneralMinimoAniBarCode;
    }

    /**
     * Sets the value of the porcentajeGeneralMinimoAniBarCode property.
     * 
     */
    public void setPorcentajeGeneralMinimoAniBarCode(int value) {
        this.porcentajeGeneralMinimoAniBarCode = value;
    }

}
