//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 11:19:40 AM COT 
//


package com.example.bytte.schemas.ServicioAutenticacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidacionEnrolamientoDocumentoRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidacionEnrolamientoDocumentoRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://casb.bytte.com.co/}RequestBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Completo" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="SoloMinucia" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="BarCodeBase64" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ImagenReverso" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="ImagenFrente" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="HuellasProceso" type="{http://casb.bytte.com.co/}ArrayOfProcesoAutenticacionCapturaHuella" minOccurs="0"/&gt;
 *         &lt;element name="ScoreProceso" type="{http://casb.bytte.com.co/}ScoreRequest" minOccurs="0"/&gt;
 *         &lt;element name="HuellasAProcesar" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidacionEnrolamientoDocumentoRequest", propOrder = {
    "completo",
    "soloMinucia",
    "barCodeBase64",
    "imagenReverso",
    "imagenFrente",
    "huellasProceso",
    "scoreProceso",
    "huellasAProcesar"
})
@XmlSeeAlso({
    ValidacionEnrolamientoDocumentoRequestBase.class
})
public class ValidacionEnrolamientoDocumentoRequest
    extends RequestBase
{

    @XmlElement(name = "Completo")
    protected boolean completo;
    @XmlElement(name = "SoloMinucia")
    protected boolean soloMinucia;
    @XmlElement(name = "BarCodeBase64")
    protected String barCodeBase64;
    @XmlElement(name = "ImagenReverso")
    protected byte[] imagenReverso;
    @XmlElement(name = "ImagenFrente")
    protected byte[] imagenFrente;
    @XmlElement(name = "HuellasProceso")
    protected ArrayOfProcesoAutenticacionCapturaHuella huellasProceso;
    @XmlElement(name = "ScoreProceso")
    protected ScoreRequest scoreProceso;
    @XmlElement(name = "HuellasAProcesar")
    protected int huellasAProcesar;

    /**
     * Gets the value of the completo property.
     * 
     */
    public boolean isCompleto() {
        return completo;
    }

    /**
     * Sets the value of the completo property.
     * 
     */
    public void setCompleto(boolean value) {
        this.completo = value;
    }

    /**
     * Gets the value of the soloMinucia property.
     * 
     */
    public boolean isSoloMinucia() {
        return soloMinucia;
    }

    /**
     * Sets the value of the soloMinucia property.
     * 
     */
    public void setSoloMinucia(boolean value) {
        this.soloMinucia = value;
    }

    /**
     * Gets the value of the barCodeBase64 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarCodeBase64() {
        return barCodeBase64;
    }

    /**
     * Sets the value of the barCodeBase64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarCodeBase64(String value) {
        this.barCodeBase64 = value;
    }

    /**
     * Gets the value of the imagenReverso property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getImagenReverso() {
        return imagenReverso;
    }

    /**
     * Sets the value of the imagenReverso property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setImagenReverso(byte[] value) {
        this.imagenReverso = value;
    }

    /**
     * Gets the value of the imagenFrente property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getImagenFrente() {
        return imagenFrente;
    }

    /**
     * Sets the value of the imagenFrente property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setImagenFrente(byte[] value) {
        this.imagenFrente = value;
    }

    /**
     * Gets the value of the huellasProceso property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfProcesoAutenticacionCapturaHuella }
     *     
     */
    public ArrayOfProcesoAutenticacionCapturaHuella getHuellasProceso() {
        return huellasProceso;
    }

    /**
     * Sets the value of the huellasProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfProcesoAutenticacionCapturaHuella }
     *     
     */
    public void setHuellasProceso(ArrayOfProcesoAutenticacionCapturaHuella value) {
        this.huellasProceso = value;
    }

    /**
     * Gets the value of the scoreProceso property.
     * 
     * @return
     *     possible object is
     *     {@link ScoreRequest }
     *     
     */
    public ScoreRequest getScoreProceso() {
        return scoreProceso;
    }

    /**
     * Sets the value of the scoreProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScoreRequest }
     *     
     */
    public void setScoreProceso(ScoreRequest value) {
        this.scoreProceso = value;
    }

    /**
     * Gets the value of the huellasAProcesar property.
     * 
     */
    public int getHuellasAProcesar() {
        return huellasAProcesar;
    }

    /**
     * Sets the value of the huellasAProcesar property.
     * 
     */
    public void setHuellasAProcesar(int value) {
        this.huellasAProcesar = value;
    }

}
